spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      url: jdbc:mysql://localhost:3306/reggie?autoReconnect=true&autoReconnectForPools=true&maxReconnects=1
      username: root
      password: love
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射 true开启
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #MyBatis-Plus 中的一项全局配置，用于指定主键ID的生成策略。ASSIGN_ID 表示手动指定主键ID值
      #即需要在代码中显式地赋值给主键ID属性，而不是由数据库自动生成。
      #当使用 ASSIGN_ID 时，需要在实体类中使用 @TableId 注解标注对应的主键属性，并设置 type 属性为 IdType.ASSIGN_ID，示例如下：
      #@TableId(value = "id", type = IdType.ASSIGN_ID)
      #private Long id;
      #需要注意的是，使用 ASSIGN_ID 时需要手动为主键ID属性赋值，因此可能存在主键冲突的风险，需要开发者自行保证主键的唯一性。
      id-type: ASSIGN_ID
server:
  port: 8080
#定义一个图片存储路径
reggie:
  path: S:\xiaosong\reggie\src\main\resources\img\